### ISSUE TITLE
[android/crash] ArtistAlbumFragment.onItemClick (line:88)

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#220] opened 2016-11-01 18:49 UTC
This one comes out rarely, still happening on build 320.

```
java.lang.NullPointerException
	at com.andrew.apollo.ui.fragments.profile.ArtistAlbumFragment.onItemClick(ArtistAlbumFragment.java:88)
	at android.widget.AdapterView.performItemClick(AdapterView.java:302)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1196)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3054)
	at android.widget.AbsListView$3.run(AbsListView.java:3812)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5584)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
	at dalvik.system.NativeStart.main(Native Method)
```

Will leave this one to @grzesiekrzaca

**Comment by grzesiekrzaca** [comment] 2016-11-28 15:09
Ok, finally found it. It requires (relatively) quick fingers. The problem is with the way the whole 2-list view is implemented. This happens when the user has clicked the fake element of the list that acts as a spacer for the visible header of the TabCarousel. 
If the user scrolls on one list so that the header is in a minimal state and the switches to the other tab the header will have to adjust to the new height giving time for the user to press the spacer resulting in a crash. 
I'll see if the header can be realigned in a better way. (If not I'll make that click ignored)

**Comment by gubatron** [comment] 2016-11-28 20:40
![success_baby](https://cloud.githubusercontent.com/assets/163977/20685082/218fe97a-b570-11e6-86fb-3d1c9a25b655.png)

**Comment by grzesiekrzaca** [comment] 2016-11-29 11:26
#269

**Comment by aldenml** [comment] 2016-11-29 19:26
This should be fixed, pending test

**Closed** 2016-12-06 16:27 UTC
Labels: android, crash
