### ISSUE TITLE
[android] FrostWire Player list of songs appears cut on Android tablets

### ISSUE THREAD

**Issue by muckachina** [frostwire/frostwire#109] opened 2016-03-24 23:25 UTC
This issue persists on FrostWire 1.7.1 (build 237).
Reference on QA: https://github.com/frostwire/qa-android/issues/65

If I have a big list of songs the list appears cut and the entire space of the screen is not being used.

![screen shot 2016-03-24 at 7 22 00 pm](https://cloud.githubusercontent.com/assets/1534723/14034046/ce7e45da-f1f5-11e5-8818-70543861a380.png)

**Comment by gubatron** [comment] 2016-05-27 19:22
I think this is not a bug.
If you look at the player on a regular phone there's also that space, it's just that the proportion is bigger.

That space has been left out on purpose as we might put Seeding and Sharing buttons in that space soon.

So all good. Closing.

**Closed by gubatron** 2016-05-27 19:22 UTC
Labels: android
