### ISSUE TITLE
[android] Lockscreen Wallpaper remains even after player stops.

### ISSUE THREAD

**Issue by kad3mlia** [frostwire/frostwire#47] opened 2016-01-05 05:16 UTC
Tested on Samsung S4/Android 5.0.1 with no SD Card without any screen lock apps/wallpaper apps.

When FrostWire is running, with the Player playing, paused, or stopped=exited, the phone's lock screen shows a track cover of last played artist. Once FrostWire is closed, the wallpaper disappears and reverts to system choice. 

FIX: It should not be showing the wallpaper on lock screen either at all or at least not when player is not actively playing. 

Several users reported as well. Cannot reproduce on Sony Xperia Z2/ Android 5.1.1. It has Sony Themes pre-installed and as default and I believe this is what's overwriting FrostWire in my case.

**Comment by gubatron** [comment] 2016-01-05 07:05
CC: @votaguz @alejandroarturom @X-NicON @dennistobar (@arubinofaux wanna do some android?)

$15 bounty for merged pull request to be paid in Bitcoin at the exchange rate of the day on Bitven.com

**Comment by marcelinkaaa** [comment] 2016-01-05 13:41
Just went over all the other apps I have on my phone. When I play something or have a player from an app open but track paused the cover is still showing on the lock screen, which makes sense as the player is still active. Seems to be a standard system thing. But as soon as the player is off - even though the app is still on - the cover should disappear. So the second part of the fix would be better :)

**Comment by gubatron** [comment] 2016-01-06 00:33
Oh, this is not a bug, now that I read it. If the player is paused it should still show it.
Thought it was showing this even though the player was completely stopped.

Is this also the case? again, showing the wallpaper when FrostWire isn't running or when FrostWire is running and the player is STOPPED (not paused, paused is ok)

**Comment by marcelinkaaa** [comment] 2016-01-06 01:53
yes, paused is ok. But as soon as the player was used once and than completely stopped and exited the wallpaper is still there on the lock screen until the end of the session.

**Comment by gubatron** [comment] 2016-01-06 02:57
**then**

**Comment by gubatron** [comment] 2016-01-11 00:28
I can now confirm this issue. Will have to look at how this code works. If we can figure this out, maybe we should make it a setting, I kind of like it seeing a different thing every time I'm about to unlock the phone.

**Closed** 2016-04-07 19:58 UTC
Labels: android, bug, help wanted (bitcoin bounty)
