### ISSUE TITLE
[android-player] Creating a New Playlist from Album does not add Album's tracks

### ISSUE THREAD

**Issue by kad3mlia** [frostwire/frostwire#49] opened 2016-01-05 05:54 UTC
**Tested on** 
FW Basic 1.6.8 build 227, Samsung S4/Android 5.0.1
FW Plus build 228, Sony Xperia Z2/ Android 5.1.1. 

**Behavior**
Creating a New Playlist when in My Music under Album, Recent, Artists or any screen that shows tracks in aggregate does create a Playlist, but does not add tracks from that screen to the Playlist. Playlist is empty.

**Steps to Reproduce**
1. Go to My Music > Albums
2. Tap on any album
3. Select Menu from upper right corner > choose New Playlist
4. Name Playlist and tap OK. 
5. Scroll back to Playlists & Check your newly created playlist

**Additional Observations**
1. The same thing happens on both phones
2. The same thing happens regardless of file format
3. Adding individual files to a New Playlist works fine
4. Adding individual files to an already existing Playlist works fine

**Comment by gubatron** [comment] 2016-01-05 07:14
CC: @votaguz @alejandroarturom @X-NicON @dennistobar (@arubinofaux wanna do some android?)

$15 bounty for merged pull request to be paid in Bitcoin at the exchange rate of the day on Bitven.com

**Comment by marcelinkaaa** [comment] 2016-01-05 13:33
We need to make sure that we are only fixing this at the inner stage, for example Recent - selected album, and not just in recent, or in artists - Kellee Maize and not just artists. When you double hold for ex. a whole album you get "Add to Playlist" and on the next dialog you can either choose your playlist or create a new one - this works as intended, so we could use that functionality in the overflow menu when inside of the artist or an album instead of 'New Playlist' only. 
Everything on the outside - when 'My Music' is on the action bar means we would add all our content to a playlist, which we don't want. So since we can not tap and hold to select multiple songs or albums it only make sense to have 'new playlist' as is now.

**Comment by kad3mlia** [comment] 2016-01-05 14:06
OK - I see what you are saying. If you logic is correct (and I think it is) then technically the current behaviour is fine and nothing is broken. 

Logically then, there should be two functions:
'New Playlist' - Creates an empty Playlist
'Add All to Playlist' - Creates a Playlists with all files on current screen or adds all files on current screen to an already existing Playlist. 

If @gubatron agrees, we should probably close this ticket and open one with Enhancement to add 'Add All to Playlist' functionality. I in the light of current workload, I would even mark it as low priority/bounty and I will explain playlist creation on support for anybody that gets confused.

**Comment by marcelinkaaa** [comment] 2016-01-05 14:10
Well, in the beginning I wanted to do just that - add "Add all to playlist" however when you go into a particular folder 'shuffle all', 'sort by' only applies to that particular album. Hence I was thinking of just having "Add to playlist" instead of both. When you add to playlist the dialog will come with an option to create a new playlist to add it too or selecting an existing one. I think by doing so we would be able to reuse some code that already exists.

**Comment by marcelinkaaa** [comment] 2016-01-05 20:49
So thinking more about it ... kademlia is right, I think keeping both is the best option. 
I started working on it and set it up so the Add to Playlist is visible in certain ProfileActivities such as Albums and Artists but still can not make it fully functional. Will work on it later. Good exercise.

**Comment by gubatron** [comment] 2016-01-05 21:23
Hi gurls.

Just took a look.

"New Playlist" is a generic button to create a new playlist and it works as expected.

When we're in a screen that shows multiple songs, we can have that second one that says "Add to playlits", so that should be an easy fix, and I think @marcelinkaaa already did it.

There's one improvement to make, and it's something I did for desktop.

When you add a bunch of songs, whatever they are to a new Playlist, the suggested name should be there for you without having to type the name.

So here's the first part of the code on desktop (for illustration purposes)

```java
public static void createNewPlaylist(final List<? extends AbstractLibraryTableDataLine<?>> lines) {
        DialogFinishedListener dialogListener = new DialogFinishedListener() {
            @Override
            public void onDialogCancelled() {
            }

            @Override
            public void onDialogOk(String playlistName) {
                if (playlistName != null && playlistName.length() > 0) {
                    final Playlist playlist = LibraryMediator.getLibrary().newPlaylist(playlistName, playlistName);
                    playlist.save();
                    LibraryMediator.instance().getLibraryPlaylists().addPlaylist(playlist);
                    LibraryMediator.instance().getLibraryPlaylists().markBeginImport(playlist);
                    Thread t = new Thread(new Runnable() {
                        public void run() {
                            addToPlaylist(playlist, lines);
                            playlist.save();
                            asyncAddToPlaylistFinalizer(playlist);
                        }
                    }, "createNewPlaylist");
                    t.setDaemon(true);
                    t.start();
                    UXStats.instance().log(UXAction.LIBRARY_PLAYLIST_CREATED);
                }
            }
        };

        FrostwireInputDialog.showInputDialog(GUIMediator.getAppFrame(),
                I18n.tr("Playlist name"),
                I18n.tr("Playlist name"),
                GUIMediator.getThemeImage("playlist"),
                suggestPlaylistName(lines), // CHECK THIS OUT
                dialogListener);
    }
```

There I have this method called `suggestPlaylistName(lines)`, this is the code:

```
private static String suggestPlaylistName(File[] mediaFiles) {
        HistoHashMap<String> artistNames = new HistoHashMap<String>();
        HistoHashMap<String> artistsAlbums = new HistoHashMap<String>();
        HistoHashMap<String> albumNames = new HistoHashMap<String>();
        HistoHashMap<String> genres = new HistoHashMap<String>();

        for (File mf : mediaFiles) {
            if (MediaPlayer.isPlayableFile(mf)) {
                TagsData mt = new TagsReader(mf).parse();
                artistNames.update(mt.getArtist());
                artistsAlbums.update(mt.getArtist() + " - " + mt.getAlbum());
                albumNames.update(mt.getAlbum());
                genres.update("(" + mt.getGenre() + ")");
            }
        }

        Entry<String, Integer>[] histogramArtistNames = artistNames.histogram();
        Entry<String, Integer>[] histogramArtistsAlbums = artistsAlbums.histogram();
        Entry<String, Integer>[] histogramAlbumNames = albumNames.histogram();
        Entry<String, Integer>[] histogramGenres = genres.histogram();

        String topArtistName = histogramArtistNames[histogramArtistNames.length - 1].getKey();
        int topArtistNameCount = histogramArtistNames[histogramArtistNames.length - 1].getValue();

        String topArtistAlbum = histogramArtistsAlbums[histogramArtistsAlbums.length - 1].getKey();
        int topArtistAlbumCount = histogramArtistsAlbums[histogramArtistsAlbums.length - 1].getValue();

        String topAlbumName = histogramAlbumNames[histogramAlbumNames.length - 1].getKey();
        int topAlbumNameCount = histogramAlbumNames[histogramAlbumNames.length - 1].getValue();

        String topGenre = histogramGenres[histogramGenres.length - 1].getKey();

        String suggestedPlaylistName = topArtistName;
        if (topArtistAlbumCount >= topArtistNameCount) {
            suggestedPlaylistName = topArtistAlbum;
        } else if (topAlbumNameCount >= topArtistNameCount) {
            suggestedPlaylistName = topAlbumName;
            if (topArtistNameCount > 3) {
                suggestedPlaylistName = topArtistName + " - " + suggestedPlaylistName;
            }
        }

        if (!topGenre.equals("()")) {
            suggestedPlaylistName = suggestedPlaylistName + " " + topGenre;
        }

        return suggestedPlaylistName;
    }
```

I invented something called `HistoHashMap`, it's a structure that has an update operation.
You tell it about a certain key that you found, and it adds it to an internal map that keeps count of how many times it happend. On the algorithm above I keep count of the album names, song titles, artists names of the list of music files given so I can try to deduct what the most common pattern is and suggest a playlist name.

`HistoHashMap` currently lives only in `package com.frostwire.gui.library;` which is inside desktop.

If you're up for it, @marcelinkaaa , we can move it somewhere inside the common/ folder and make use of it to improve the "New Playlist" pre-written text. I think those are the kind of details that make you love an app which are not so obvious, being on a cellphone, it's a PITA to have to type the name of an artist, album, etc, it's just amazing if you open that dialog an the app is smart enough to type it for you.

That algorithm above uses a `TagReader`, which is a class that can open audio files to analize their metadata, in the case of android, it should be easier because we already have that data parsed for us.

**Comment by marcelinkaaa** [comment] 2016-01-05 21:29
This is just a visual set up was not able to connect functionality; ContextMenu used when you long press on the item to get "Add to playlist" works great but I can not seem to find a way to connect it to the action bar overflow menu. I tired using your AddToPlaylistMenuAction.java in android not apollo in, in couple of different ways, but I was just able to show the list of playlists but nothing happened on click. 
 
https://github.com/marcelinkaaa/frostwire/tree/apollo-playlist-fix

**Comment by gubatron** [comment] 2016-01-20 00:12
I've been doing a lot of work now on this and I'm a bit more familiar with the codebase.
As part of this fix I'll attempt a refactor that should eliminate a ton of repeated code in about 17 fragment classes.

**Comment by gubatron** [comment] 2016-01-20 00:13
this was a can of worms that was opened and it should be cleaned.

**Comment by aldenml** [comment] 2016-02-08 23:18
@gubatron Comparing branches I have: 110 changed files with 2,094 additions and 4,976 deletions.

I can't fully follow all the refactor+new features you made and I'm worry about it. It's my impression that such a big change should support a fundamental new product feature, not an additional menu item. If the act of adding this menu item, requieres such a big change, then we need to balance the risk of doing it vs immediate effective gain. The player is a very delicate and pseudo-stable component.

@marcelinkaaa @kad3mlia I would like to hear your opinions too. Thanks

**Comment by gubatron** [comment] 2016-02-09 03:01
If you come to the lab tomorrow I'll give you a walkthrough of the changes.
I believe it's a lot better now and in better shape for future fixes and additions.

**Comment by aldenml** [comment] 2016-02-09 03:30
OK, let's review this together

**Closed** 2016-03-25 21:40 UTC
Labels: android, bug, WIP
