### ISSUE TITLE
Ref. MM-Playlist-7 / MM-Recent-5 / MM-Artists-6 / MM-Albums-6 'Add to queue' - Not working properly

### ISSUE THREAD

**Issue by muckachina** [frostwire/frostwire#733] opened 2018-06-15 22:17 UTC
Updating issue for FrostWire 2.0.5-build-530

This are the details that still remain on this feature:

**Minimized Player does not appear in some scenarios (refreshing issue) and songs not queued after the Player Stops**

Example to reproduce:

1- Go to My Music and start playing any song
2- Add another songs to queue
3- Stop the player
4- Select any other audio again and "add to queue" the audio > **you will notice the minimized player does not display unless you Exit My Music and go to a different screen**
5- When you see the Player minimized after going to a different screen Play the song and press 'next' > **You should notice the songs you added to queue in step 4 did not appear as queued**

More scenarios not working properly for this feature (build 535):

**Songs are not added to queue when they don't belong to the same album:**

Go to My Music > Last Added or Songs or Recent or Playlists and select one song to play
While playing a song select any other song within the same list that does not belong to the same album and click "Add to queue"
Click the button 'Next' and the song that will start is not the one you added to queue

Initial reference at: https://github.com/frostwire/qa-android/issues/135#issuecomment-387494001

**Comment by gubatron** [comment] 2018-06-16 01:28
"Songs are not added to queue when they don't belong to the same album"

that second bug you mention isn't really a bug. Songs added to the queue are added to the end of the queue. I see the song being added, and when I hit next, the next song on the queue is played. If the queue has more than one song, the last song you added will be the last and therefore not played, if you have a queue of 1 song, I see it being added, and it will be the next played.

I have to play more with the first scenario.

**Comment by muckachina** [comment] 2018-06-18 17:19
Actually is not related to songs in the same album, that particular scenario affects songs from the same album. 

Try this:

1) Make sure there are no songs added to queue before when you launch FW
2) Go to My Music > Songs and select one song to play
3) While playing a song **select any other song within the same list that is not the next in the list, it could belong to the same album or not and click "Add to queue"**
4) Click the button 'Next' and the song that will start is not the one you added to queue, it's actually the next song in the list of "Songs", **you will have to go next > next > next... till you actually reach the audio file you added to queue**


**To reproduce the issue with 'Same Albums' try this:**

1) Make sure there are no songs added to queue or playing when launching FW!
2) Go to Albums and select an album that has multiple songs
3) Start playing the first or second audio of that Album list
4) Go to My Music > Artists and select a song from there that does not belong to the Album playing and click "Add to queue"
5) When you click "Next" the next song playing is the next song in the list of the Album not the song added to queue. **Unless you say I've to play the entire lists within 'Songs' before playing the audio added to queue that's an issue**
6) Then Do the same steps from 2 to 4 and this time when you click "Next" the next song playing it's actually the one you added to queue! so definitely there is an issue here.

Let me know what should be the right behavior (what happens at Step 5 or what happens at Step 6)

**Comment by marcelinkaaa** [comment] 2018-06-18 21:02
Minimized Player does not appear in some scenarios (refreshing issue) and songs not queued after the Player Stops - yes, still does that to me in build 541. 

When it comes to your last comment - "While playing a song select any other song within the same list that is not the next in the list, it could belong to the same album or not and click "Add to queue"" - if it is within the same list it is automatically added in the player's queue, right? The entire queue changes when you start playing a song from a different list, and all songs from that list form a brand new queue, even if you added songs to queue manually before. It is basically overwritten. And by adding a song from the same list - you are simply adding it again but this time it will be located at the end of the queue list. 
So when you talk about clicking next -> next .... in point 4, is it because you added manually some song from the same list and now it is at the end of the list, the queue? In this case it is how the player works and not a bug. But probably not the best use of queues. 


"To reproduce the issue with 'Same Albums' try this"
5.  "Unless you say I've to play the entire lists within that Album before playing the audio added to queue that's an issue" - yes, it is by design. 
So as discussed when you start playing a song from an album with multiple songs - the current queue is overwritten with that album (which is not the best solution either). So that action happens on pressing play from another location; but when you add to queue it always puts the new song at the end of the currently added list. 
If you wanted the song to play next - there is an entry in options for that and its called - "Play next" - this inserts that song in the next position on the queue.

**Comment by marcelinkaaa** [comment] 2018-06-18 21:07
The whole queue behavior could be slightly updated to resemble that of some modern players. 
Attaching a screenshot from Spotify. They distinguish between songs added manually to the queue and those added there automatically when a user selects to play an album or a playlist. So that when you change the album from which you are currently playing the songs you are not losing the tracks you added manually to the queue (and those manual tracks are played next in ordered added - before you move to the rest of the songs from the playlist/album. 

![img_8891](https://user-images.githubusercontent.com/2339972/41562241-467cf52c-7309-11e8-8f4a-deebb05cb5c1.jpg)

**Comment by muckachina** [comment] 2018-06-19 13:16
Oki about the behavior at -step 5 @marcelinkaaa but there is an issue anyway, check -step 6, in that case 

If I'm playing songs from an entire Album > then adding to queue something outside that album > then pressing "next" on Player > the behavior should be "the next song within the Album" till reaching the end and then play what is 'queued' (according to "by design rule"), in that case it doesn't happen so, sometimes it does it right (first try when there is nothing in the queue), sometimes doesn't.

**Comment by marcelinkaaa** [comment] 2018-06-19 14:36
Step 6, I remember not having that issue. But will check in all the phones in a bit. Maybe I missed something.

**Comment by muckachina** [comment] 2018-06-19 19:35
Updating here...

I was running yesterday afternoon and this morning an old version of FW Basic installed from the Play Store (fml)... My bad, although good queued behavior it's solved 

So, step number 5 on **second scenario** is Ok > thats' not an issue.

**Scenario 1** If the entire list has to play first even all My Audios before playing queued songs > It's Ok not an issue neither (although confusing to me, as Natalie says, not the best use for this feature)

Here one of the scenarios where **minimized Player is not being displayed**

1- Go to My Music and start playing any song
2- Add another songs to queue
3- Stop the player
4- Select any other audio again and "add to queue" the audio > **you will notice the minimized player does not display unless you Exit My Music and go to a different screen**

**Comment by gubatron** [comment] 2018-06-23 13:46
@votaguz I've not had a chance to go over this. Was there a misunderstanding of how the feature works, or is there a bug after all?

**Comment by votaguz** [comment] 2018-06-23 16:43
Both. Was a misunderstanding but there is a little bug related to the mini player:

> you will notice the minimized player does not display unless you Exit My Music and go to a different screen

**Comment by gubatron** [comment] 2018-06-23 22:43
ok, I'm going to close this ticket then.

Pleas open a new ticket votaguz, make sure to prefix the title with "[android]" and add a succinct title on it, assign yourself as responsible.

**Closed by gubatron** 2018-06-23 22:43 UTC
