### ISSUE TITLE
[search] LimeTorrents is leaking HTML tags in search result titles

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#745] opened 2018-07-04 11:00 UTC
<img width="272" alt="screen shot 2018-07-04 at 4 59 04 am" src="https://user-images.githubusercontent.com/163977/42273714-35848f60-7f47-11e8-869b-773c7391bca2.png">

**Comment by aldenml** [comment] 2018-07-04 15:23
fixed with https://github.com/frostwire/frostwire/commit/93aafd896bcea8eea94fccd391f27d84b983cf7b

**Comment by aldenml** [comment] 2018-07-04 15:24
reopening to testing @muckachina

**Comment by muckachina** [comment] 2018-07-05 20:36
I can't reproduce this issue here Alden, testing now version 6.7.0 updated today... I'll keep testing and re-open in case I see something similar. @gubatron Is this related to the report from a user on FB? let me know If you did a particular search

**Closed by muckachina** 2018-07-05 20:36 UTC
Labels: bug, common
